# Generated by Django 5.2.17 on 2026-09-22 23:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrigenSernapesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_origen', models.CharField(db_index=True, max_length=50)),
                ('tipo_origen', models.CharField(blank=True, max_length=80)),
                ('codigo_agente', models.CharField(blank=True, max_length=50)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_recepcion', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_origen_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('peso_recepcion_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_recepcion', to='trazabilidad.especie')),
                ('origen_sernapesca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_recepcion', to='trazabilidad.origensernapesca')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='trazabilidad.recepcion')),
            ],
        ),
    ]
