# Generated by Django 5.2.17 on 2026-09-23 00:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadFrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('MANTENCION', 'Mantención'), ('TUNEL_CONGELADO', 'Túnel de congelado'), ('ALMACENAMIENTO', 'Almacenamiento')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_termino', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_finalizados', to=settings.AUTH_USER_MODEL)),
                ('iniciado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_iniciados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('DIVIDIDA', 'Dividida'), ('CONSUMIDA', 'Consumida'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_creadas', to=settings.AUTH_USER_MODEL)),
                ('detalle_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='trazabilidad.detallerecepcion')),
                ('partida_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subpartidas', to='trazabilidad.partidaproceso')),
            ],
        ),
        migrations.CreateModel(
            name='MermaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='trazabilidad.eventoproceso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_registradas', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='trazabilidad.partidaproceso')),
            ],
        ),
        migrations.AddField(
            model_name='eventoproceso',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='trazabilidad.partidaproceso'),
        ),
        migrations.CreateModel(
            name='Pesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_hora_evento', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pesajes', to='trazabilidad.eventoproceso')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesajes', to='trazabilidad.partidaproceso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesajes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventoproceso',
            name='tipo_proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='trazabilidad.tipoproceso'),
        ),
        migrations.CreateModel(
            name='EstanciaPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('ingresado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias_partida_ingresadas', to=settings.AUTH_USER_MODEL)),
                ('retirado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estancias_partida_retiradas', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias_frio', to='trazabilidad.partidaproceso')),
                ('unidad_frio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias_partidas', to='trazabilidad.unidadfrio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventoproceso',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_hora_termino__isnull', True), ('fecha_hora_termino__gte', models.F('fecha_hora_inicio')), _connector='OR'), name='evento_fin_mayor_igual_inicio'),
        ),
        migrations.AddConstraint(
            model_name='estanciapartida',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_hora_salida__isnull', True), ('fecha_hora_salida__gte', models.F('fecha_hora_ingreso')), _connector='OR'), name='estancia_partida_salida_mayor_igual_ingreso'),
        ),
    ]
