# Generated by Django 5.2.17 on 2026-09-23 00:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0002_tipoproceso_unidadfrio_eventoproceso_partidaproceso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('peso_nominal_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['peso_nominal_kg', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Correccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_afectada', models.CharField(max_length=100)),
                ('identificador_registro', models.CharField(max_length=100)),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('motivo', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=80, unique=True)),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='trazabilidad.especie')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_elaboracion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg_utilizada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_lote', to='trazabilidad.partidaproceso')),
                ('lote_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='trazabilidad.loteproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caja', models.CharField(max_length=100, unique=True)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_armado', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_registradas', to=settings.AUTH_USER_MODEL)),
                ('lote_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='trazabilidad.loteproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('peso_unitario_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones', to='trazabilidad.caja')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones_caja', to='trazabilidad.presentacionbolsa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loteproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__isnull', True), ('fecha_vencimiento__gte', models.F('fecha_elaboracion')), _connector='OR'), name='lote_vencimiento_mayor_igual_elaboracion'),
        ),
        migrations.AddConstraint(
            model_name='composicioncaja',
            constraint=models.UniqueConstraint(fields=('caja', 'presentacion'), name='composicion_caja_presentacion_unica'),
        ),
    ]
