# Generated by Django 5.2.17 on 2026-09-24 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0003_presentacionbolsa_correccion_loteproduccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaRutaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_ruta', to='trazabilidad.tipoproceso')),
            ],
            options={
                'ordering': ['ruta_id', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='eventoproceso',
            name='etapa_ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='trazabilidad.etaparutaproceso'),
        ),
        migrations.CreateModel(
            name='RutaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('predeterminada', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_proceso', to='trazabilidad.especie')),
            ],
            options={
                'ordering': ['especie__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='etaparutaproceso',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='trazabilidad.rutaproceso'),
        ),
        migrations.AddField(
            model_name='partidaproceso',
            name='ruta_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='trazabilidad.rutaproceso'),
        ),
        migrations.AddConstraint(
            model_name='rutaproceso',
            constraint=models.UniqueConstraint(fields=('especie', 'nombre'), name='ruta_nombre_unico_por_especie'),
        ),
        migrations.AddConstraint(
            model_name='etaparutaproceso',
            constraint=models.UniqueConstraint(fields=('ruta', 'orden'), name='etapa_orden_unico_por_ruta'),
        ),
        migrations.AddConstraint(
            model_name='etaparutaproceso',
            constraint=models.CheckConstraint(condition=models.Q(('orden__gt', 0)), name='etapa_orden_positivo'),
        ),
    ]
