# Generated by Django 5.2.17 on 2026-09-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0005_catalogo_procesamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mermaproceso',
            name='tipo',
            field=models.CharField(choices=[('MERMA', 'Merma'), ('DESCARTE', 'Descarte'), ('PERDIDA', 'Pérdida')], default='MERMA', max_length=10),
        ),
    ]
