# Generated by Django 5.2.17 on 2026-09-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0006_mermaproceso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='ruta_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='trazabilidad.rutaproceso'),
        ),
        migrations.AddConstraint(
            model_name='consumolote',
            constraint=models.UniqueConstraint(fields=('partida', 'lote_produccion'), name='consumo_unico_partida_lote'),
        ),
    ]
