# Generated by Django 5.2.17 on 2026-09-26 18:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0007_loteproduccion_ruta_proceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='codigo_caja',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='peso_total_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='composicioncaja',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='composicion_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='composicioncaja',
            constraint=models.CheckConstraint(condition=models.Q(('peso_unitario_kg__gt', 0)), name='composicion_peso_positivo'),
        ),
        migrations.AddConstraint(
            model_name='presentacionbolsa',
            constraint=models.CheckConstraint(condition=models.Q(('peso_nominal_kg__gt', 0)), name='presentacion_peso_positivo'),
        ),
    ]
