# Generated by Django 5.2.17 on 2026-09-26 19:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0009_presentaciones_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='peso_neto_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='peso neto real (kg)'),
        ),
    ]
