# Generated by Django 5.2.17 on 2026-09-28 19:31

import django.core.validators
from django.db import migrations, models


def asignar_codigos(apps, schema_editor):
    especies = apps.get_model("trazabilidad", "Especie").objects.using(schema_editor.connection.alias)
    pendientes = list(especies.filter(codigo_lote__isnull=True).order_by("pk").values_list("pk", flat=True))
    usados = set(especies.exclude(codigo_lote__isnull=True).values_list("codigo_lote", flat=True))
    disponibles = [f"{n:02d}" for n in [*range(1, 100), 0] if f"{n:02d}" not in usados]
    if len(pendientes) > len(disponibles):
        raise RuntimeError("No alcanzan los códigos de dos dígitos para las especies existentes. Revise el catálogo antes de migrar.")
    for pk, codigo in zip(pendientes, disponibles):
        especies.filter(pk=pk).update(codigo_lote=codigo)


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0011_caja_identificador_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='codigo_lote',
            field=models.CharField(blank=True, help_text='Código estable de dos dígitos para generar lotes. Obligatorio antes de crear un lote.', max_length=2, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9]{2}\\Z', 'El código de especie debe tener exactamente dos dígitos.')]),
        ),
        migrations.RunPython(asignar_codigos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='especie',
            constraint=models.CheckConstraint(condition=models.Q(('codigo_lote__isnull', True), ('codigo_lote__regex', '^[0-9]{2}$'), _connector='OR'), name='especie_codigo_lote_dos_digitos'),
        ),
    ]
