# Generated by Django 5.2.17 on 2026-09-30 03:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0012_especie_codigo_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadfrio',
            name='umbral_alerta_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de permanencia antes de alertar. Vacío significa sin alerta configurada.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='unidadfrio',
            constraint=models.CheckConstraint(condition=models.Q(('umbral_alerta_horas__isnull', True), ('umbral_alerta_horas__gt', 0), _connector='OR'), name='unidad_frio_umbral_positivo'),
        ),
    ]
