# Generated by Django 5.2.17 on 2026-09-23 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trazabilidad', '0003_presentacionbolsa_correccion_loteproduccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baja', to='trazabilidad.caja')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_caja_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_despacho', models.DateTimeField()),
                ('destino', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_despacho', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_despacho', to='trazabilidad.caja')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.despacho')),
            ],
        ),
        migrations.CreateModel(
            name='EstanciaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias_inventario', to='trazabilidad.caja')),
                ('ingresado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_ingresadas_inventario', to=settings.AUTH_USER_MODEL)),
                ('retirado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_retiradas_inventario', to=settings.AUTH_USER_MODEL)),
                ('unidad_frio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias_cajas', to='trazabilidad.unidadfrio')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_hora_salida__isnull', True), ('fecha_hora_salida__gte', models.F('fecha_hora_ingreso')), _connector='OR'), name='estancia_caja_salida_mayor_igual_ingreso')],
            },
        ),
    ]
