# Generated by Django 5.2.17 on 2026-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='despacho',
            name='pais_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='despacho',
            name='rut_destinatario',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='despacho',
            name='tipo_destino',
            field=models.CharField(blank=True, choices=[('NACIONAL', 'Nacional'), ('EXPORTACION', 'Exportación')], max_length=20),
        ),
        migrations.AddField(
            model_name='despacho',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
