# Generated by Django 5.2.17 on 2026-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_despacho_fecha_documento_despacho_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajacaja',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PERDIDA', 'Pérdida'), ('DANO', 'Daño'), ('DESCARTE', 'Descarte'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
