# Generated by Django 5.2.17 on 2026-09-30 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_roles_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Usuario creado'), ('ROL', 'Rol cambiado'), ('RESET', 'Contraseña restablecida'), ('DESACTIVACION', 'Usuario desactivado'), ('REACTIVACION', 'Usuario reactivado'), ('CONTRASENA', 'Contraseña cambiada por el usuario')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('rol_anterior', models.CharField(blank=True, max_length=80)),
                ('rol_nuevo', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora', '-pk'],
            },
        ),
    ]
